### ISSUE TITLE
ReadMe updates

### ISSUE THREAD

**Issue by Rup-Royofficial** [NKumar141/railgadi#6]
There were a few grammatical errors and spelling mistakes within the Readme file. I have submitted a PR rectifying the errors and adding fluency to a various paragraphs in the Readme File

**Comment by NKumar141** [comment]
Good Work ! . Committed this into the repository 👍👍

**Comment by Rup-Royofficial** [comment]
Hey, I'm sorry, but could you add/assign me this,
I know PR is merged and the issue is closed but I forgot to ask to be assigned!
Sorry for the trouble!
